[package]
name = "whale"
version = "0.1.0"
authors = ["Robert Yi <robert@dataframe.ai>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
skim = "0.8.2"
clap = "2.26.2"
