name: Python-CI

on:
  push:
    paths:
    - "pipelines/**"
  pull_request:
    paths:
    - "pipelines/**"
    - ".github/workflows/python-ci.yml"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        mkdir -p ~/.whale/manifests
        echo '${{ secrets.BIGQUERY_JSON }}' > /var/tmp/credentials.json

        python -m pip install --upgrade pip
        pip install -r pipelines/requirements.txt
        pip install -r pipelines/dev-requirements.txt
        pip install pipelines/.
    - name: Run tests
      run: |
        make test
      env:
        GOOGLE_APPLICATION_CREDENTIALS: /var/tmp/credentials.json
    - name: Code coverage
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
