name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        mkdir -p ~/.whale/manifests
        echo '${{ secrets.BIGQUERY_JSON }}' > /var/tmp/credentials.json
        pip install mock
        pip install -r pipelines/requirements.txt
        pip install pipelines/.
        pip install flake8
        pip install pytest-cov
        pip install pytest
    - name: Run tests
      run: |
        make test
      env:
        GOOGLE_APPLICATION_CREDENTIALS: /var/tmp/credentials.json
    - name: Code coverage
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
