name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        token: ${{ secrets.PAT }}
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install .
        pip install flake8
        pip install pytest-cov
    - name: Run tests
      run: |
        make test
    - name: Code coverage
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
